ALTER TABLE visitas
  ADD COLUMN IF NOT EXISTS socio_id INT REFERENCES socios(socio_id),
  ADD COLUMN IF NOT EXISTS correo VARCHAR(150),
  ADD COLUMN IF NOT EXISTS telefono VARCHAR(20),
  ADD COLUMN IF NOT EXISTS mayor_16 BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS observaciones TEXT;

CREATE INDEX IF NOT EXISTS idx_visitas_socio_id ON visitas(socio_id);
